import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

import { stringify as stringifyYaml } from 'yaml';

import {
  ATLASPEC_PACKAGE_VERSION,
  compileMapLibre,
  loadDocument,
} from '../src/index.js';
import type {
  AtlaspecV01Document,
  CompilationDecision,
  Diagnostic,
  MapLibreStyle,
} from '../src/index.js';

const OUTPUT_PATH = resolve('demo/data/compiler-examples.json');

interface DemoExample {
  id: string;
  title: string;
  eyebrow: string;
  verdict: 'rejected' | 'compiled';
  summary: string;
  document: string;
  diagnostics: Diagnostic[];
  decisions: CompilationDecision[];
  artifact: {
    renderer: 'MapLibre';
    source_ids: string[];
    layers: Array<{
      id: string;
      type: unknown;
      source?: unknown;
      minzoom?: unknown;
      maxzoom?: unknown;
    }>;
    excerpt: string | null;
  } | null;
}

async function buildExamples(): Promise<{
  schema_version: '1';
  package_version: string;
  boundary: string;
  examples: DemoExample[];
}> {
  const flood = (await loadDocument(
    'examples/flood-risk.atlas.yaml',
  )) as AtlaspecV01Document;
  const shelter = (await loadDocument(
    'examples/shelter-capacity.atlas.yaml',
  )) as AtlaspecV01Document;

  const unsafeCount = structuredClone(flood);
  unsafeCount.map = 'district-population';
  unsafeCount.title = 'Population count by district';
  unsafeCount.description =
    'An intentionally unsafe raw-count choropleth used to demonstrate semantic rejection.';
  unsafeCount.intent.primary_message =
    'Compare district population without normalizing for polygon area.';
  delete unsafeCount.data.fields.flood_probability;
  unsafeCount.data.fields.population_count = {
    source: 'districts',
    path: 'population',
    measurement: 'quantitative',
    semantic_type: 'count',
    unit: 'people',
    normalization: 'none',
    range: [0, 500000],
  };
  if (unsafeCount.encoding.color !== undefined) {
    unsafeCount.encoding.color.field = 'population_count';
  }
  unsafeCount.constraints.raw_count_choropleth = 'reject';

  return {
    schema_version: '1',
    package_version: ATLASPEC_PACKAGE_VERSION,
    boundary:
      'Generated by the repository compiler. The browser explains recorded deterministic output; it does not run an LLM.',
    examples: [
      compileExample(
        'unsafe-count',
        'Reject a misleading choropleth',
        'SEMANTIC LINT',
        'Raw counts on unequal-area polygons are rejected before a renderer artifact exists.',
        unsafeCount,
      ),
      compileExample(
        'flood-probability',
        'Compile a normalized probability map',
        'DETERMINISTIC COMPILE',
        'A declared probability range and explicit missing-data policy compile into renderer-valid layers.',
        flood,
      ),
      compileExample(
        'shelter-capacity',
        'Enforce area-proportional symbols',
        'CARTOGRAPHIC POLICY',
        'The compiler derives square-root radius scaling so symbol area—not radius—tracks capacity.',
        shelter,
      ),
    ],
  };
}

function compileExample(
  id: string,
  title: string,
  eyebrow: string,
  summary: string,
  document: AtlaspecV01Document,
): DemoExample {
  const compilation = compileMapLibre(document);
  if (!compilation.ok) {
    return {
      id,
      title,
      eyebrow,
      verdict: 'rejected',
      summary,
      document: stringifyYaml(document, { lineWidth: 88 }).trimEnd(),
      diagnostics: compilation.diagnostics,
      decisions: [],
      artifact: null,
    };
  }

  return {
    id,
    title,
    eyebrow,
    verdict: 'compiled',
    summary,
    document: stringifyYaml(document, { lineWidth: 88 }).trimEnd(),
    diagnostics: compilation.diagnostics,
    decisions: compilation.decisions,
    artifact: summarizeStyle(compilation.style, document.family),
  };
}

function summarizeStyle(
  style: MapLibreStyle,
  family: AtlaspecV01Document['family'],
): NonNullable<DemoExample['artifact']> {
  const representative =
    style.layers.find((layer) =>
      family === 'proportional-symbol'
        ? String(layer.id).endsWith('-symbols')
        : String(layer.id).endsWith('-fill'),
    ) ?? style.layers.at(-1);

  return {
    renderer: 'MapLibre',
    source_ids: Object.keys(style.sources),
    layers: style.layers.map((layer) => ({
      id: String(layer.id),
      type: layer.type,
      ...('source' in layer ? { source: layer.source } : {}),
      ...('minzoom' in layer ? { minzoom: layer.minzoom } : {}),
      ...('maxzoom' in layer ? { maxzoom: layer.maxzoom } : {}),
    })),
    excerpt:
      representative === undefined
        ? null
        : JSON.stringify(representative, null, 2),
  };
}

async function main(): Promise<void> {
  const serialized = `${JSON.stringify(await buildExamples(), null, 2)}\n`;
  if (process.argv.includes('--check')) {
    const current = await readFile(OUTPUT_PATH, 'utf8');
    if (current !== serialized) {
      throw new Error(
        'demo/data/compiler-examples.json is stale; run npm run demo:generate',
      );
    }
    console.log('VERIFIED compiler-generated demo examples');
    return;
  }

  await writeFile(OUTPUT_PATH, serialized, 'utf8');
  console.log(`WROTE ${OUTPUT_PATH}`);
}

await main();
